name: "assume role poc"
on:
  push:
    branches:
      - main
permissions:
  id-token: write

jobs:
  list_s3_buckets:
   name: "list s3 buckets"
   runs-on: ubuntu-latest
   environment: development
   steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.DEV_ARN_ROLE }}
        role-session-name: OIDCSession
        aws-region: us-east-1
    - name: "List S3"
      run: | 
        aws s3 ls
        aws sts  get-caller-identity
        aws iam list-attached-role-policies --role-name github-s3-role


